#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (forever) {
		if (getDistanceValue(distanceMM) > 70) {
			setMotor(motor1, 50);
			setMotor(motor6, 50);
		} else {
			stopAllMotors();
			wait(1, seconds);
			setMotor(clawMotor, 50);
			wait(2, seconds);
			if (getTouchLEDValue(touchLED) == true) {
				setTouchLEDColor(touchLED, colorRed);
				setMotor(armMotor, 50);
				wait(3, seconds);
				setMotor(clawMotor, -50);
				wait(5, seconds);
				setMotor(armMotor, -50);
				wait(2, seconds);
			} else {
				setMotor(clawMotor, -50);
			}
		}
	}
}
