#pragma config(Sensor, port2,  touchLED,      sensorVexIQ_LED)
#pragma config(Sensor, port5,  colorDetector, sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  distanceMM,    sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,    sensorNone)
#pragma config(Motor,  motor1, leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6, rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor3, clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task OnDriveMode()
{
	repeat (forever) {
		if(getDistanceValue(distanceMM) >= 300) //Keep going until this reaches 30 cm
		{
			resetMotorEncoder(clawMotor);
			setMotorTarget(clawMotor, 0, 50);
			resetMotorEncoder(armMotor);
			setMotorTarget(armMotor, 0, 50);
			setMultipleMotors(50, motor1, motor6, , );
			waitUntil (getDistanceValue(distanceMM) <= 150);
			stopAllMotors();

			wait(2, seconds);
			setMotorTarget(armMotor, -1200, 30);
			setMotorTarget(clawMotor,-100, 50);
			wait(6, seconds);
			setMotorTarget(clawMotor,100, 50);
			wait(3, seconds);

			if ((getColorValue(colorDetector)<29) || (getColorValue(colorDetector)>219)) //detects red hue
			{
				displayTextLine(1, "Pick this hue= %d", getColorValue(colorDetector) );
		
				setServoTarget(armMotor, 0);
				wait(3, seconds);
				setMotorTarget(clawMotor,-500, 50);
			}
			else
			{
				displayTextLine(1, "Drop this hue= %d", getColorValue(colorDetector) );
				setMotorTarget(clawMotor,-500, 50);
				wait(3, seconds);
				setServoTarget(armMotor, 0);
			}
			
		}		
	}//end of forever
}

task main()
{
	repeat(forever)
	{
		startTask(OnDriveMode);
		while(true)
		{
			sleep(25); // Keep the program alive, but let the other tasks have the processor by "sleeping"
		}
	}
}