#pragma config(Sensor, port5,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Motor,  motor7, leftFrontWheel, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor8, rightFrontWheel,tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor9, leftRearWheel,  tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor10,rightRearWheel, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Sensor, port11, touchLED,       sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------
A basic loop to detect a range of hue values.
The color sensor returns hue as a 0-255 value.
This program classifies all colors within the following
ranges, prints hue value, makes sounds and behaves as below:

RED:       0 to 20 OR 220 to 255 -> Motor STOPS for 3 seconds
GREEN:    51 to 219 						 -> Motor moves FORWARD forever
                                    at 40% speed until it finds Red or Yellow
YELLOW:   21 to 50							 -> Motor moves REVERSE
                                    at 20% speed for 3 seconds
--------------------------------------------------------------------------------------*/

task main()
{
	while (true)
	{
		int currentHueValue = getColorValue(colorDetector);
		//Keep checking hue value every 25 milli-seconds

		if( (currentHueValue >=0 && currentHueValue < 20)
			  ||
			  (currentHueValue > 219 && currentHueValue <= 255))
			  //For e.g., Stops when hue values like 8,14,246
		{
			//If this detects Red Color, make a power sound
			displayTextLine(1, "Hue value=%d",currentHueValue);
			displayTextLine(2, "This has REDDISH shade, STOP!!! for 3 secs");
			playSound(soundPowerOff2);

			//Set the LED color to matching hue and
			//keep it blinking for 2 seconds ON, half-sec OFF
			setTouchLEDHue(touchLED, currentHueValue);
			setTouchLEDBlinkTime(touchLED, 40, 10);

			setMotorSpeed(leftFrontWheel,0);
			setMotorSpeed(rightFrontWheel,0);
			setMotorSpeed(leftRearWheel,0);
			setMotorSpeed(rightRearWheel,0);

			//Bring all motors speed to 0 and sleep for
			//3000 milli-seconds (or 3 seconds)
			sleep(3000);
		}
		else if((currentHueValue > 51) && (currentHueValue <= 219))
		//Go forward for e.g., when hue values like Green (59, 64, 43)
    //or Blue (150,157) or White (127) or Black(171)
		{
			displayTextLine(1, "Hue value=%d",currentHueValue);
			displayTextLine(2, "GREEN/BLUE/WHITE/BLACK shade, GO GO GO!");
			playSound(soundCarAlarm2);

			setTouchLEDHue(touchLED, currentHueValue);
			setTouchLEDBlinkTime(touchLED, 40, 10);

			setMotorSpeed(leftFrontWheel,40);
			setMotorSpeed(rightFrontWheel, 40);
			setMotorSpeed(leftRearWheel, 40);
			setMotorSpeed(rightRearWheel,40);
			//The motors now moves forward at 40% speed
		}
		else if((currentHueValue > 21) && (currentHueValue <= 50))
		//Go reverse for e.g., when hue values like 38, 43
		{
			displayTextLine(1, "Hue value=%d",currentHueValue);
			displayTextLine(2, "This has YELLOWish shade, REVERSE for 3 secs!");
			playSound(soundCarAlarm4);

			setTouchLEDHue(touchLED, currentHueValue);
			setTouchLEDBlinkTime(touchLED, 40, 10);

		//The motors now move at 20% speed in reverse for 3 seconds
			setMotorSpeed(leftFrontWheel,-20);
			setMotorSpeed(rightFrontWheel, -20);
			setMotorSpeed(leftRearWheel, -20);
			setMotorSpeed(rightRearWheel, -20);
			sleep(3000);
		}

		//Small delay to allow color sensor to detect any changes in color
		sleep(25);
	}//forever or until restart
}
