#pragma config(Sensor, port5,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Motor,  motor7,          leftFrontWheel, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor8,          rightFrontWheel, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Motor,  motor9,          leftRearWheel, tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor10,         rightRearWheel, tmotorVexIQ, openLoop, reversed, encoder)
#pragma config(Sensor, port11,  touchLED,      sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
A basic loop to detect a range of hue values. The VEX IQ Color sensor returns hue as a 0-255 value.
This is different than normal "hue" readings which range from 0-359.

This program will use the following ranges to print on the LCD screen the current color it sees:
Red: 0 to 50 / 220 to 255
Green: 51 to 130
Blue 131 to 219

Using "else if" and the "&&" (Logical AND), we can make ranges of values to detect different colors/conditions.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                            [Location]
Port 5              colorDetector       VEX IQ Color                          Color Detector (Hue Color Mode)
Port 7              leftFrontWheel      VEX IQ Motor                          Left Front motor
Port 8              rightFrontWheel     VEX IQ Motor                          Right Front motor (reversed)
Port 9              leftRearWheel       VEX IQ Motor                          Left Rear motor
Port 10             rightRearWheel      VEX IQ Motor                          Right Rear motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true) //Do this forever
	{
		if(getColorValue(colorDetector) < 50)//RED
		{
			playSound(soundPowerOff2);

			//If this detects Red Color, print on LED display
			int currentHueValue = getColorValue(colorDetector);
			displayTextLine(1, "I see RED!");  //Command to Write to the LCD Screen
			displayTextLine(2, "Its hue value is %d",currentHueValue);  //Command to print hue value on screen

			//Set the LED color red
			setTouchLEDHue(touchLED, currentHueValue); //This is more accurate
			setTouchLEDBlinkTime(touchLED, 40, 10);

			waitUntilMotorStop(leftFrontWheel);
			waitUntilMotorStop(rightFrontWheel);
			waitUntilMotorStop(leftRearWheel);
			waitUntilMotorStop(rightRearWheel);

		}
		else if((getColorValue(colorDetector) > 50) && (getColorValue(colorDetector) <= 130))//GREEN
		{

		  playSound(soundSiren2);

			//Detect a Green Color
			int currentHueValue = getColorValue(colorDetector);
			displayTextLine(1, "I see GREEN!");  //Command to Write to the LCD Screen
			displayTextLine(2, "Its hue value is %d",getColorValue(colorDetector));  //Command to print hue value on screen

			//Set the LED color green
			setTouchLEDHue(touchLED, currentHueValue);
			setTouchLEDBlinkTime(touchLED, 40, 10);

			//Reset the current position in the motor encoder to zero.
			resetMotorEncoder(leftFrontWheel);
			resetMotorEncoder(rightFrontWheel);
			resetMotorEncoder(leftRearWheel);
			resetMotorEncoder(rightRearWheel);

			//Set motor to run 5 counts at power level 40.
			moveMotorTarget(leftFrontWheel, 5000, 40);
			moveMotorTarget(rightFrontWheel, 5000, 40);
			moveMotorTarget(leftRearWheel, 5000, 40);
			moveMotorTarget(rightRearWheel, 5000, 40);

			//Blocking command prevents program from continuing until movement is complete.
			waitUntilMotorStop(leftFrontWheel);
			waitUntilMotorStop(rightFrontWheel);
			waitUntilMotorStop(leftRearWheel);
			waitUntilMotorStop(rightRearWheel);

		}
		else if((getColorValue(colorDetector) > 131) && (getColorValue(colorDetector) <= 219))
		{
			playSound(soundSiren2);

			//Detect a Blue Color
			int currentHueValue = getColorValue(colorDetector);
			displayTextLine(1, "I see BLUE!");  //Command to Write to the LCD Screen
			displayTextLine(2, "Its hue value is %d",getColorValue(colorDetector));  //Command to print hue value on screen

			//Set the LED color green
			setTouchLEDHue(touchLED, currentHueValue);
			setTouchLEDBlinkTime(touchLED, 40, 10);

			//Reset the current position in the motor encoder to zero.
			resetMotorEncoder(leftFrontWheel);
			resetMotorEncoder(rightFrontWheel);
			resetMotorEncoder(leftRearWheel);
			resetMotorEncoder(rightRearWheel);

			//Set motor to run 5 counts at power level -40.
			moveMotorTarget(leftFrontWheel, -5000, -20);
			moveMotorTarget(rightFrontWheel, -5000, -20);
			moveMotorTarget(leftRearWheel, -5000, -20);
			moveMotorTarget(rightRearWheel, -5000, -20);

			//Blocking command prevents program from continuing until movement is complete.
			waitUntilMotorStop(leftFrontWheel);
			waitUntilMotorStop(rightFrontWheel);
			waitUntilMotorStop(leftRearWheel);
			waitUntilMotorStop(rightRearWheel);
		}
		else if(getColorValue(colorDetector) > 219)
		{
			//Detect a Red Color (second half of the range)
			int currentHueValue = getColorValue(colorDetector);
			displayTextLine(1, "I see RED!");  //Command to Write to the LCD Screen
			displayTextLine(2, "Its hue value is %d",getColorValue(colorDetector));  //Command to print hue value on screen

			//Set the LED color green
			setTouchLEDHue(touchLED, currentHueValue);
			setTouchLEDBlinkTime(touchLED, 40, 10);

			waitUntilMotorStop(leftFrontWheel);
			waitUntilMotorStop(rightFrontWheel);
			waitUntilMotorStop(leftRearWheel);
			waitUntilMotorStop(rightRearWheel);

		}
		sleep(25); //Small delay to allow color sensor to detect any changes in color
	}
}
